version: "3"

services:

  redis:
    container_name: redis_async_api_v1
    image: redis:7.0.0
    volumes:
      - redis_api_vol:/data
    env_file:
      - ../.env

  postgres:
    container_name: postgres
    image: postgres:13-alpine3.15
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ../.env

  nginx:
    container_name: nginx_async_api_v1
    build: ../nginx
    env_file:
      - ../.env
    volumes:
      - ./nginx:/nginx
      - static_volume:/app/static
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - redis

  auth:
    container_name: auth
    build: ..
    entrypoint:
      - ./boot.sh
    env_file:
      - ../.env
    depends_on:
      - redis
      - postgres
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "5775:5775/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  fastapi_solution:
    container_name: fastapi_solution
    build: ..
    working_dir: /fastapi_solution
    env_file:
      - ../.env
    depends_on:
      - redis
      - elasticsearch
      - postgres

volumes:
  redis_api_vol:
  elastic_api_vol:
  postgres_volume:
  static_volume: