FROM python:3.10.4-slim-buster
WORKDIR auth
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip  --no-cache-dir
COPY auth/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY auth .
CMD python wsgi.py

