access_roles_list = {
    "anonymous": [
        "/auth/api/v1/login_to_social_network/",
        "/api/v1/auth/",
        "/apidocs/",
        "/favicon.ico",
        "/flasgger_static/<path:filename>",
        "/apispec_1.json",
        "/auth/api/v1/login",
        "/auth/api/v1/set_user",
        "/auth/api/v1/check_token",
        "/auth/api/v1/user_history",
        "/api/v1/films/",
        "/api/v1/genres/",
        "/api/openapi",
        "/api/v1/films/",
        "/auth/api/v1/check_access",
    ],
    "subscriber": [

        "/apidocs/",
        "/flasgger_static/<path:filename>",
        "/apispec_1.json",
        "/auth/api/v1/get_user",
        "/auth/api/v1/password_update",
        "/auth/api/v1/get_users",
        "/auth/api/v1/login",
        "/auth/api/v1/logout",
        "/auth/api/v1/refresh",
        "/auth/api/v1/check_token",
        "/api/v1/films/<uuid:UUID>/",
        "/api/v1/films/",
        "/api/v1/films/search/",
        "/api/v1/genres/<uuid:UUID>/",
        "/api/v1/genres/",
        "/api/v1/person/<uuid:UUID>/",
        "/api/v1/person/<uuid:UUID>/film/",
        "/api/v1/person/search/",
        "/api/openapi",
        "/favicon.ico",
        "/auth/api/v1/user_history",
    ],
}
